Azure Solution Architect Meeting 22.10
AzureCommunityPL/group pull request #117
Opened 2020-10-16 13:39 UTC by maciejgos

Opis zadania z przykładem rozwiązania

2020-10-16 16:53 UTC, kaluzaaa approved these changes

2020-10-16 16:54 UTC, kaluzaaa commented
@aryll @eklime zobaczcie czy niema litrówek ;-)

2020-10-16 18:00 UTC, aryll commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +- 2) droższa ale bardziej zabezpieczona
tutaj numerowanie zgłupiało
![image](https://user-images.githubusercontent.com/5950108/96292935-40459d00-0fea-11eb-968c-30324a3c7697.png)

2020-10-16 18:06 UTC, aryll commented
@maciejgos zastanawiam się czy to dobry pomysł zamieszczać nasze rozwiązanie przed spotkaniem - ogólnie teraz to i tak za dużo osób nie jest świadomych że tutaj będziemy zamieszczać rozwiązania więc na razie nie ma to znaczenia ale później może to innym sugerować rozwiązanie i nie wiem czy to takie dobre 🤷

2020-10-16 21:08 UTC, eklime requested changes

2020-10-16 21:08 UTC, eklime commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +1. Review przygotowanych rozwiązań.
Review -> Przegląd

2020-10-16 21:08 UTC, eklime commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +# Discussion
Discussion -> Dyskusja

2020-10-16 21:08 UTC, eklime commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +## Review projektu architektury
Review -> Przegląd

2020-10-16 21:08 UTC, eklime commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +Firma chce zabezpieczyć komunikację sieciową pomiędzy zasobami, które są hostowane na Azure oraz zasobami postawionymi na on-premie. Cała infrastruktura powinna być dostępna tylko z sieci firmowej, o
"postawionymi na on-premie" -> "uruchomionymi w on-premises" lub "uruchomionymi w sieci lokalnej firmy"
"wraz z zasobami" -> koniec zdania, kropka. Wywalić "natomias" i zacząć zdanie od "Zaproponowane:

2020-10-16 21:08 UTC, eklime commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +- 1) stosunkowo bezpieczna i tania oraz
"oraz" niepotrzebne

2020-10-17 08:26 UTC, maciejgos commented
@aryll bardziej ma to na celu zachęcenie ludzi żeby coś wrzucili i tak to może przykładowo wyglądać. Co do sugerowania rozwiązania to fakt może to mieć taki efekt... Z drugiej strony jesteśmy już dość blisko terminu więc nie jestem przekonany czy jakaś duża grupa się zasugeruje tym ;)

2020-10-17 08:46 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +- 2) droższa ale bardziej zabezpieczona
Faktycznie coś się rozjechało -> poprawiłem

2020-10-17 08:46 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +1. Review przygotowanych rozwiązań.
Poprawiłem

2020-10-17 08:47 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +# Discussion
Poprawiłem

2020-10-17 08:47 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +## Review projektu architektury
Poprawiłem

2020-10-17 08:47 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +Firma chce zabezpieczyć komunikację sieciową pomiędzy zasobami, które są hostowane na Azure oraz zasobami postawionymi na on-premie. Cała infrastruktura powinna być dostępna tylko z sieci firmowej, o
Przeredagowałem

2020-10-17 08:47 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-10-22.md
> +- 1) stosunkowo bezpieczna i tania oraz
poprawione

2020-10-17 09:38 UTC, eklime approved these changes

2020-10-17 09:39 UTC, merged