Notatka 10.12.2020
AzureCommunityPL/group pull request #178
Opened 2020-12-14 18:09 UTC by maciejgos

Hej wrzucam część notatki ze spotkania.
Do dodania: 
- [ ] Link do nagrania

2020-12-15 08:26 UTC, aryll requested changes

2020-12-15 08:26 UTC, aryll commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +- Autoryzacja i autentykacja w App Service: https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to
uwierzytelnianie?  😄

2020-12-15 08:26 UTC, aryll commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +## Linki
Brakuje mi tutaj trochę tego linku
https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios

2020-12-15 08:34 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +- Autoryzacja i autentykacja w App Service: https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to
Ok poprawię wieczorem :)

2020-12-15 08:34 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +## Linki
Był poprzednio w notatkach dlatego uznałem, że nie ma go już co kolejny raz wrzucać

2020-12-15 10:15 UTC, aryll commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +## Linki
No dobra, niech będzie

2020-12-15 17:57 UTC, maciejgos commented on meetings/azure-solutions-architect/azure-solutions-architect-qa-2020-12-10.md
> +- Autoryzacja i autentykacja w App Service: https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to
Poprawiłem

2020-12-15 20:10 UTC, aryll approved these changes

2020-12-18 09:34 UTC, kaluzaaa approved these changes

2020-12-18 09:34 UTC, merged